### ISSUE TITLE
Fix MODS date display in search results

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1140]
Applies to BCE dates, and AD dates earlier than 1000. Dates are displaying correctly in the record view, but not in results. 

Affects Roman Coins collection (BCE), as well as Walters Manuscripts (AD).

SW-1543

The date in the Title[Data]  will be completed when:
- [x] solrconfig change deployed to prod (sul-dlss/solrmarc-sw#123)
- [x] MODS data reindexed with sul-dlss/sw-indexer-service#52
- [x] #1186 is deployed

The imprint_display update requires:
- [x] PR for sul-dlss/stanford-mods#52
- [x] new release of stanford-mods gem
- [x] PR for sul-dlss/sw-indexer-service  to utilize new code in stanford-mods to populate imprint_display field
- [x] MODS data reindexed

**Comment by ndushay** [comment]
This is related to:

sul-dlss/stanford-mods#56  early date display
sul-dlss/sw-indexer-service#43 dates for roman coins
sul-dlss/stanford-mods#53  u and uu display

**Comment by ndushay** [comment]
And also related to sul-dlss/stanford-mods#52

**Comment by ndushay** [comment]
@jvine  - close this if you agree.    Where the search result image went, I don't know -- separate issue.

AFAICT, the MODS records with early dates look great — the search results imprint statement and Title[Date] are better now.  

## Before
![walters before](https://cloud.githubusercontent.com/assets/96775/13198017/694f7bbe-d7b2-11e5-99a9-88bdc0c3b91f.png)

## After
![walters after](https://cloud.githubusercontent.com/assets/96775/13198027/9b513670-d7b2-11e5-96ac-f5fed322aca5.png)

## Roman Coins no imprint  but yes, Title[Date]
![more roman coins](https://cloud.githubusercontent.com/assets/96775/13198044/faf40c1a-d7b2-11e5-8e48-7f07a24f1653.png)

## Roman Coins with imprint
![more roman coins with imprint](https://cloud.githubusercontent.com/assets/96775/13198054/4cb65f9e-d7b3-11e5-97c3-6f7a17b35650.png)

**Comment by jvine** [comment]
:+1:
