### ISSUE TITLE
Production rollout checklist

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/SearchWorks#1725]
## Friday
- [x] Update shared configs (for EDS, auth, feedback, etc.) (at least some by @drh-stanford)
  - [x] searchworks-stage (see https://github.com/sul-dlss/shared_configs/pull/365, https://github.com/sul-dlss/shared_configs/pull/364)
  - [x] searchworks-prod (see https://github.com/sul-dlss/shared_configs/pull/366, https://github.com/sul-dlss/shared_configs/pull/363)
  - [x] searchworks-bots (see https://github.com/sul-dlss/shared_configs/pull/367, https://github.com/sul-dlss/shared_configs/pull/362)
  - [x] ~others?~ (put a note for follow on tasks in the week that include getting other envs up-to-date)
- [x] Do we need to change our monitoring at all? (https://github.com/sul-dlss/SearchWorks/issues/1740)
- [x] Rebase on top of master (@jkeck)
- [x] Cut a tagged release (@jkeck)
- [x] Deploy to stage (@jkeck)

## Monday
- [x] Deploy to production (6am PT) (@mejackreed)
  * Bot deploy first, then user facing nodes

## Rest of week
- [ ] Update all preview environments (uat, gryphon, etc)
- [x] Monitor EDS cache usage to ensure we don't fill up the disk

**Comment by jkeck** [comment]
We will update the preview environments one-by-one as needed.
