### ISSUE TITLE
Add event tracking for various UI features

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#2117]
More or less in priority order...

- [x] IIIF badge clicks 'n drags
- [ ] Featured resources on home page

Would be useful to group these by context: results, record view, selection list
- [ ] Request
- [ ] Stackmap
- [ ] Cite
- [ ] Send to (text, email, refworks, endnote, printer)
- [ ] View / sort / per page
- [ ] Preview
- [ ] Select / Select all
- [ ] Check availability toggle
- [ ] side-nav-minimap
- [ ] more... links
- [ ] Facet toggle

Record view
- [ ] Browse nearby (click, scroll)
- [ ] Links in content blocks, such as the context panels (collection, appears in)
- [ ] Librarian view

Selection lists
- [ ] Catalog vs. Articles+ - views? menu/tab clicks? 
- [ ] logged-in vs. not

**Comment by camillevilla** [comment]
11/26: prioritize the following
- Cite
- Stackmap
- Browse nearby

**Comment by camillevilla** [comment]
Great! @aeschylus picked off priority items in #2219. Unassigning and moving this to the backlog for now.
