### ISSUE TITLE
HathiTrust ETAS support - what can we do?

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/SearchWorks#2431]
[Link to analysis document with questions](https://docs.google.com/document/d/1bJrFa_ouDXK9hJwQgfwAPuG3BU1sLKkwxEl8t40Waeo/edit)

[Link to design proposal](https://docs.google.com/document/d/1VffReZdPfX7j8cQ6erBOckRHTOxqzW1Ie3ryIUlFTrw/edit#)

## TODO
- [x] Link on Show Page
- [x] Link on Results Page
- [x] Online "label" on Results Page
- [x] Add to online facet
- [x] Add notice/message to online facet
- [x] Single volume vs multi volume behavior
- [x] Feature Flag all the things

## Questions
- [x] Do we need to conditionally show ETAS links based on our own online access [YES!]

**Comment by jvine** [comment]
> Do we need to conditionally show ETAS links based on our own online access?

Yes.

From design proposal:   "Links to HathiTrust records will be made visible in SearchWorks only for matches that do not have an existing online source."

**Comment by jkeck** [comment]
And, just to clarify, we mean full text online sources?  Also, do we need to do anything special when a document has SFX links (where, if I'm not mistaken, we may not know for certain if the resulting SFX results will contain full-text links or not)?

**Comment by jvine** [comment]
Yes, full text sources. SFX... researching.

**Comment by jvine** [comment]
I think if we have an SFX link we believe that we have access to full text, whether it's a limited range or free access or through one or more subscription services. HT may end up having coverage that we don't, but I don't believe we can permit overlap.
