### ISSUE TITLE
Menu updates (related to LibGuides & Covid)

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#2552]
### Goals
- replace/update the current Library Services menu with a Help menu to
   - focus on user goals and reflect actual usage
   - remove dead links; reduce redundancy & dependence on content that is likely to be removed
- add a highlighted COVID-19 link to a prominent and semi-permanent location
   - remove dependency on the banner for long-term navigation

### Mockup
<img width="415" alt="Screen Shot 2020-09-23 at 4 02 36 PM" src="https://user-images.githubusercontent.com/6945691/94085158-2387c200-fdbc-11ea-8a51-a651653e8379.png">

### Tasks
- [x] Rename `Library services` to `Help`
- [x] Replace the menu content 
   - this seems to be just HTML in the code? so I've pasted below the HTML I used to create the mockup
- [x] Add `COVID-19 Libraries update`link to the `.navbar-left` group and fancy it up
   - link is to https://library.stanford.edu/status
   - background-color = `$poppy: #e98300;`
   - font-color = black
   - add 15px left and right padding

### Bento variation
https://github.com/sul-dlss/sul-bento-app/issues/397
Bento will have the same changes, with some links removed from the Help menu:
- `Using SearchWorks`
- `If we don't have it` group

### Menu HTML
- adds a `.menugroup` class to unlinked section headers
   - apply the same styling as the linked menu options, and add `font-variant: all-small-caps;`
- adds `.stanford-only` and `.sr-only` text to the restricted menu options 

```
<ul class="dropdown-menu sul-services-menu" role="menu" aria-labelledby="searchNavbarTopMenu">
<li>
    <span class="menugroup">Need help?</span>
  <ul>
      
      <li>
        <a role="menuitem" href="https://library.stanford.edu/chat" class="stanford-only" title="limited to Stanford community">Chat with us  <span class="sr-only"> (limited to Stanford community)</span></a>
      </li>
      <li>
        <a role="menuitem" href="https://library.stanford.edu/ask/email/reference">Email a reference question</a>
      </li>
<li>
        <a role="menuitem" href="https://library.stanford.edu/people">Find a subject specialist</a>
      </li>
<li></li><li>
        <a role="menuitem" href="https://guides.library.stanford.edu/searchworks">Using SearchWorks</a>
      </li>
         </ul>
  </li>  
<li>
    <span class="menugroup">Connection</span>
    <ul>
      <li>
        <a role="menuitem" href="https://library.stanford.edu/using/connect-campus">Connect to e-resources</a>
      </li>
    <li>
        <a role="menuitem" href="https://library.stanford.edu/ask/email/connection-problems">Report a connection problem</a>
      </li>

    </ul>
  </li>
  
  <li>
    <span class="menugroup">If we don't have it</span>
    <ul>
      <li>
        <a role="menuitem" href="https://library.stanford.edu/using/interlibrary-borrowing">Interlibrary borrowing</a>
      </li>
   <li>
        <a role="menuitem" href="https://library.stanford.edu/suggest_purchase" class="stanford-only" title="limited to Stanford community">Suggest a purchase <span class="sr-only"> (limited to Stanford community)</span></a>
      </li>
          </ul>
  </li>
   <li>
    <a role="menuitem" href="https://library-status.stanford.edu/">Check system status</a>
  </li>
</ul>
```
