### ISSUE TITLE
Determine if SmartText search is enabled and indicate this to the user

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/SearchWorks#2561]
### Context
We've enabled SmartText search which is a mode that is only executed under when the search query yields zero results.  This happens automatically and is not apparent to the user.  This can, however, yield millions of results for certain queries (as it appears that one of the changes that is done under the hood is to "OR" the search terms). 

### Tasks
- [ ] Determine if we can tell from the gem/response if SmartText search has been executed (we may need to request that EBSCO add this feature if not already available)
- [ ] Add a note to the search results display when this mode is enabled
- [ ] DON'T call it SmartText (from the users perspective)

**Comment by cbeer** [comment]
Context: Came up through feedback; people pasted citations that got 0 results and EBSCO does a thing. Enabling the EBSCO thing yielded a lot of search results, but it would be better as an opt-in thing. #2574 is a PR to enable that, but needs text + design (and naming?). EBSCO now has a thing to know if you’re in SmartText now, which might be useful.

So.. more design needed to explore these options.

**Comment by saseestone** [comment]
Closing this for now as public services staff determined that they would prefer that we give better instructions to users on the zero results page, and NOT enable EBSCO's thing (i.e.SmartText).
