### ISSUE TITLE
Call numbers in List view

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#816]
**Part 1: list of call numbers**
- [x] List one line per library+location with holdings, like so:
  - library : location : first call number 
- [x] If the library has MHLD but no barcoded items show:
  - library : location : (no call number)
- [x] Markup is one flat unordered list. color: #767676. font-size: 0.9em

**Part 2: styling of document list**
- [x] remove margin between the documents in the list
- [x] reduce padding inside the document border to 7px
- [x] give "Select" and "Preview" one column, and align "Preview" to the bottom - might work like this, maybe?
  - row 1: title | select
  - row 2: list | preview

**Part 3: preview**
- [x] make the preview behave in the same way it does on gallery view: insert a row between the documents, and display the preview there

**Part 4: hover behaviour**
- [x] when the cursor is over a callnumber list, display a tooltip at the top of that list
- [x] background color is same as preview button: #539a98;
  (The bootstrap tooltip uses aria-labelledby, which is good. If you use a different implementation, let me know.)

Future:  Depending what kind of use this view gets, we may make the list itself clickable to open the preview.

![brief-list-w-call-numbers](https://cloud.githubusercontent.com/assets/6945691/4083820/4d1b7c38-2f00-11e4-831f-a1c3ae9e13b8.png)
